version: "3.8"

services:
  dcmqi:
    image: qiicr/dcmqi:latest
    container_name: dcmqi_container
    volumes:
      - ./docker_data:/data
      - ./docker_function.py:/app/docker_function.py
    entrypoint: tail -f /dev/null
